# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20181103_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(default='default.png', max_length=255, upload_to='image/%Y/%m', verbose_name='图片'),
        ),
    ]
