# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 08:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='restore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Comment', verbose_name='回复对象'),
        ),
        migrations.AddField(
            model_name='comment',
            name='restore_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restore', to=settings.AUTH_USER_MODEL, verbose_name='回复的用户'),
        ),
    ]
